baseURL = "https://mitmproxy.org/"
languageCode = "en-us"
title = "mitmproxy.org"
theme = "mitmproxy"
publishDir = "../public"
relativeURLs = true

[params]
  version = "10.1.0"

[indexes]
  tag = "tags"

[markup.goldmark.renderer]
unsafe = true
